[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "P4PSignaling"
dynamic = ["version"]
description = "A signaling server for p4p network."
dependencies = [
    "P4PNodeGossiper @ git+https://github.com/stsaria/P4PNodeGossiper.git",
    "P4PCore @ git+https://github.com/stsaria/P4PCore.git",
    "dotenv"
]
license = { file = "LICENSE" }
requires-python = ">=3.13"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"